#!/usr/bin/env bash
set -eu

case $debugConfig in
    none)
        echo 0
        ;;

    *)
        jobid=$(grep <stderr "[m]apred.JobClient: Running job: job_.*" | sed 's/.* Running job: //')
        hadoop fs -test -e giraph-debug-traces/$jobid
        hadoop fs -lsr giraph-debug-traces/$jobid | awk '{print $5}' | awk '{sum+=$1}  END{print sum}'
esac
